/**
 * KonoDeck - No SaaS Up Your Deck
 * Local LLM-powered presentation generator with structured agent
 */

import { slideAgent } from './agent.js';

const $ = id => document.getElementById(id);

// State
const state = {
  engine: null,
  modelLoaded: false,
  slides: [],
  currentSlide: 0,
  generating: false
};

// Initialize
document.addEventListener('DOMContentLoaded', async () => {
  setupEventListeners();
  await initLLM();
});

// Setup event listeners
function setupEventListeners() {
  $('sendBtn').addEventListener('click', handleSend);
  $('chatInput').addEventListener('keydown', (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  });

  $('presentBtn').addEventListener('click', startPresentation);
  $('exitPresentation').addEventListener('click', exitPresentation);
  $('prevSlide').addEventListener('click', () => navigateSlide(-1));
  $('nextSlide').addEventListener('click', () => navigateSlide(1));
  $('newDeckBtn').addEventListener('click', resetDeck);
  $('regenerateBtn').addEventListener('click', () => regenerateCurrentSlide());

  // Edit controls
  $('editTitle')?.addEventListener('input', updateSlideFromEdit);
  $('editContent')?.addEventListener('input', updateSlideFromEdit);
  $('editStyle')?.addEventListener('change', updateSlideFromEdit);

  // Keyboard navigation
  document.addEventListener('keydown', (e) => {
    if ($('presentationMode').style.display !== 'none') {
      if (e.key === 'ArrowRight' || e.key === ' ') navigateSlide(1);
      if (e.key === 'ArrowLeft') navigateSlide(-1);
      if (e.key === 'Escape') exitPresentation();
    }
  });
}

// Initialize Local LLM (WebLLM)
async function initLLM() {
  updateLoadingStatus('Checking WebGPU support...');

  // Check WebGPU
  if (!navigator.gpu) {
    updateLoadingStatus('WebGPU not supported. Using agent templates.');
    await delay(1000);
    finishLoading(false);
    return;
  }

  updateProgress(10);
  updateLoadingStatus('Loading local AI model...');

  try {
    const { CreateMLCEngine } = await import('https://esm.run/@mlc-ai/web-llm');

    // Use Llama 3.2 1B for faster loading
    const modelId = 'Llama-3.2-1B-Instruct-q4f16_1-MLC';

    state.engine = await CreateMLCEngine(modelId, {
      initProgressCallback: (progress) => {
        const pct = Math.round(progress.progress * 100);
        updateProgress(10 + pct * 0.85);
        updateLoadingStatus(progress.text || `Loading model: ${pct}%`);
      }
    });

    // Connect engine to agent
    slideAgent.setEngine(state.engine);

    updateProgress(100);
    updateLoadingStatus('AI ready!');
    await delay(500);
    finishLoading(true);

  } catch (e) {
    console.error('WebLLM init failed:', e);
    updateLoadingStatus('Using agent templates (LLM unavailable)');
    await delay(1000);
    finishLoading(false);
  }
}

function updateProgress(pct) {
  $('progressBar').style.width = `${pct}%`;
}

function updateLoadingStatus(msg) {
  $('loadingStatus').textContent = msg;
}

function finishLoading(llmReady) {
  state.modelLoaded = llmReady;
  $('loadingScreen').style.display = 'none';
  $('mainInterface').style.display = 'flex';
  $('mainInterface').style.flexDirection = 'column';
  $('mainInterface').style.height = '100vh';

  if (llmReady) {
    $('modelBadge').textContent = 'Llama 3.2 1B Ready';
    $('modelBadge').style.background = 'rgba(6, 214, 160, 0.2)';
  } else {
    $('modelBadge').textContent = 'Template Mode';
    $('modelBadge').style.background = 'rgba(255, 107, 53, 0.2)';
    $('modelBadge').style.color = '#ff6b35';
  }

  // Auto-generate initial deck
  autoGenerateDeck();
}

// Auto-generate deck on load
async function autoGenerateDeck() {
  state.generating = true;
  addMessage('assistant', '<span class="generating">Auto-generating your deck...</span>', true);

  try {
    const result = await slideAgent.generate();

    if (result.success && result.slides) {
      state.slides = result.slides;
      renderSlides();
      updateLastMessage(`${result.message || 'Deck ready!'} 🚂\n\nTell me about your audience and I'll customize it.`);
    }
  } catch (e) {
    console.error('Auto-generate error:', e);
    updateLastMessage('Deck generated! Tell me about your audience to customize it. 🥰');
  }

  state.generating = false;
}

// Handle chat send
async function handleSend() {
  const input = $('chatInput');
  const message = input.value.trim();
  if (!message || state.generating) return;

  input.value = '';
  addMessage('user', message);

  state.generating = true;
  addMessage('assistant', '<span class="generating">Customizing deck...</span>', true);

  try {
    // Use agent to generate/customize
    const result = await slideAgent.generate(message);

    if (result.success && result.slides) {
      state.slides = result.slides;
      renderSlides();
    }

    updateLastMessage(result.message || 'Deck updated! Check out the new slides. 🚂');

  } catch (e) {
    console.error('Generation error:', e);
    updateLastMessage('Had some trouble there. Try again?');
  }

  state.generating = false;
}

// Regenerate current slide
async function regenerateCurrentSlide() {
  if (state.generating) return;

  const index = state.currentSlide;
  state.generating = true;

  // Show regenerating state
  const thumb = document.querySelectorAll('.slide-thumb')[index];
  if (thumb) thumb.style.opacity = '0.5';

  try {
    const result = await slideAgent.regenerate(index, {
      style: $('editStyle')?.value
    });

    if (result.success && result.slide) {
      state.slides[index] = result.slide;
      renderSlides();
      showSlidePreview(index);
    }
  } catch (e) {
    console.error('Regenerate error:', e);
  }

  if (thumb) thumb.style.opacity = '1';
  state.generating = false;
}

// Update slide from edit controls
function updateSlideFromEdit() {
  const slide = state.slides[state.currentSlide];
  if (!slide) return;

  const title = $('editTitle')?.value || '';
  const content = $('editContent')?.value || '';
  const style = $('editStyle')?.value || 'bullets';

  slide.title = title;
  slide.style = style;

  // Parse content based on style
  if (style === 'bullets') {
    slide.content = content.split('\n').filter(l => l.trim());
  } else if (style === 'stats') {
    // Parse stats from content
    const lines = content.split('\n').filter(l => l.trim());
    slide.stats = lines.map(l => {
      const [value, ...rest] = l.split(' ');
      return { value, label: rest.join(' ') };
    });
  } else if (style === 'comparison') {
    // Simple split for comparison
    const lines = content.split('\n').filter(l => l.trim());
    const mid = Math.floor(lines.length / 2);
    slide.bad = lines.slice(0, mid);
    slide.good = lines.slice(mid);
  } else {
    slide.content = content;
  }

  renderSlides();
}

// Render slides grid
function renderSlides() {
  const grid = $('slidesGrid');
  grid.innerHTML = state.slides.map((slide, i) => `
    <div class="slide-thumb ${i === state.currentSlide ? 'active' : ''}" onclick="selectSlide(${i})">
      <span class="slide-thumb-number">${i + 1}</span>
      <div class="slide-thumb-content">
        <div class="slide-thumb-title">${slide.title || ''}</div>
        <div style="font-size: 8px; color: #8080a0; margin-top: 4px;">${slide.style}</div>
      </div>
    </div>
  `).join('');

  $('slideCount').textContent = `${state.slides.length} slides`;

  if (state.slides.length > 0) {
    showSlidePreview(state.currentSlide);
  }
}

// Select slide
window.selectSlide = function(index) {
  state.currentSlide = index;
  document.querySelectorAll('.slide-thumb').forEach((el, i) => {
    el.classList.toggle('active', i === index);
  });
  showSlidePreview(index);
};

// Show slide preview
function showSlidePreview(index) {
  const slide = state.slides[index];
  if (!slide) return;

  const preview = $('slidePreview');
  preview.innerHTML = renderSlideContent(slide, true);

  $('editControls').style.display = 'block';
  $('editTitle').value = slide.title || '';
  $('editStyle').value = slide.style || 'bullets';

  // Format content for editing
  if (Array.isArray(slide.content)) {
    $('editContent').value = slide.content.join('\n');
  } else if (slide.stats) {
    $('editContent').value = slide.stats.map(s => `${s.value} ${s.label}`).join('\n');
  } else if (slide.bad && slide.good) {
    $('editContent').value = [...slide.bad, '---', ...slide.good].join('\n');
  } else {
    $('editContent').value = slide.content || '';
  }
}

// Render slide content
function renderSlideContent(slide, isPreview = false) {
  // CSS handles preview scaling via .slide-preview .slide
  const scale = '';

  switch (slide.style) {
    case 'hero':
      return `
        <div class="slide hero" style="${scale}">
          <div class="slide-title">${slide.title}</div>
          <div class="slide-content">${slide.content || ''}</div>
        </div>
      `;

    case 'bullets':
      const bullets = Array.isArray(slide.content)
        ? slide.content.map(b => `<li>${b}</li>`).join('')
        : `<li>${slide.content}</li>`;
      return `
        <div class="slide bullets" style="${scale}">
          <div class="slide-title">${slide.title}</div>
          <ul class="slide-content">${bullets}</ul>
        </div>
      `;

    case 'comparison':
      return `
        <div class="slide comparison" style="${scale}">
          <div class="slide-title">${slide.title}</div>
          <div class="comparison-grid">
            <div class="comparison-side bad-side">
              <h3 style="color: #ef4444; margin-bottom: 16px;">❌ SaaS</h3>
              ${(slide.bad || []).map(b => `<p>• ${b}</p>`).join('')}
            </div>
            <div class="comparison-side good-side">
              <h3 style="color: #06d6a0; margin-bottom: 16px;">✅ P2P</h3>
              ${(slide.good || []).map(g => `<p>• ${g}</p>`).join('')}
            </div>
          </div>
        </div>
      `;

    case 'stats':
      return `
        <div class="slide stats" style="${scale}">
          <div class="stats-grid">
            ${(slide.stats || []).map(s => `
              <div>
                <div class="stat-value">${s.value}</div>
                <div class="stat-label">${s.label}</div>
              </div>
            `).join('')}
          </div>
        </div>
      `;

    case 'quote':
      return `
        <div class="slide quote" style="${scale}">
          <div class="slide-content">"${slide.content}"</div>
          ${slide.author ? `<div class="slide-author">— ${slide.author}</div>` : ''}
        </div>
      `;

    case 'cta':
      return `
        <div class="slide cta" style="${scale}">
          <div class="slide-title">${slide.title}</div>
          <div class="slide-content">${slide.content || ''}</div>
          <div class="cta-button">${slide.button || 'Get Started'}</div>
        </div>
      `;

    default:
      return `
        <div class="slide bullets" style="${scale}">
          <div class="slide-title">${slide.title || 'Untitled'}</div>
          <div class="slide-content">${slide.content || ''}</div>
        </div>
      `;
  }
}

// Presentation mode
function startPresentation() {
  if (state.slides.length === 0) return;

  state.currentSlide = 0;
  $('presentationMode').style.display = 'block';
  renderPresentationSlide();
}

function exitPresentation() {
  $('presentationMode').style.display = 'none';
}

function navigateSlide(direction) {
  const newIndex = state.currentSlide + direction;
  if (newIndex >= 0 && newIndex < state.slides.length) {
    state.currentSlide = newIndex;
    renderPresentationSlide();
    renderSlides(); // Update thumbnail selection
  }
}

function renderPresentationSlide() {
  const slide = state.slides[state.currentSlide];
  $('slideContainer').innerHTML = renderSlideContent(slide, false);
  $('slideIndicator').textContent = `${state.currentSlide + 1} / ${state.slides.length}`;
}

// Chat helpers
function addMessage(role, content, isGenerating = false) {
  const messages = $('chatMessages');
  const div = document.createElement('div');
  div.className = `message ${role}`;
  div.innerHTML = `<div class="message-content">${content}</div>`;
  if (isGenerating) div.id = 'generatingMessage';
  messages.appendChild(div);
  messages.scrollTop = messages.scrollHeight;
}

function updateLastMessage(content) {
  const msg = $('generatingMessage');
  if (msg) {
    msg.querySelector('.message-content').innerHTML = content.replace(/\n/g, '<br>');
    msg.removeAttribute('id');
  }
}

// Reset deck
function resetDeck() {
  state.slides = [];
  state.currentSlide = 0;
  slideAgent.context = { audience: null, industry: null, painPoints: [], features: [] };

  $('chatMessages').innerHTML = '';
  autoGenerateDeck();
}

// Utility
function delay(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

// Expose for debugging
window.konodeck = { state, slideAgent };
